version: "3"
services:
  stackuni: 
    stdin_open: true
    tty: true
    build: .
    ports:
     - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    # -./.env
    